import type { Address } from "viem";

// Deployed on Sepolia
export const ORION_MOMENTUM_SERIES_ADDRESS: Address =
  "0x85FEffb3fa01366f475A02F53Cf8B9C3518eDC7f";

export const ORION_MOMENTUM_SERIES_ABI = [
  { inputs: [], name: "AlreadySettled", type: "error" },
  { inputs: [], name: "AuctionExists", type: "error" },
  { inputs: [], name: "AuctionLocked", type: "error" },
  { inputs: [], name: "AuctionMissing", type: "error" },
  { inputs: [], name: "AuctionNotActive", type: "error" },
  { inputs: [], name: "AuctionNotSettled", type: "error" },
  { inputs: [], name: "BidExists", type: "error" },
  { inputs: [], name: "BidMissing", type: "error" },
  { inputs: [], name: "BondAlreadyClaimed", type: "error" },
  { inputs: [], name: "BondMismatch", type: "error" },
  { inputs: [], name: "InvalidAmount", type: "error" },
  { inputs: [], name: "InvalidDuration", type: "error" },
  { inputs: [], name: "NoBidders", type: "error" },
  { inputs: [], name: "NoWinner", type: "error" },
  { inputs: [], name: "NotSeller", type: "error" },
  { inputs: [], name: "NotWinner", type: "error" },
  { inputs: [], name: "RevealAlreadyEnabled", type: "error" },
  { inputs: [], name: "RevealNotEnabled", type: "error" },
  { inputs: [], name: "WinnerMustPay", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "string", name: "auctionId", type: "string" },
    ],
    name: "AuctionCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "string", name: "auctionId", type: "string" },
      { indexed: true, internalType: "address", name: "seller", type: "address" },
      { indexed: false, internalType: "uint256", name: "endTime", type: "uint256" },
    ],
    name: "AuctionCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "string", name: "auctionId", type: "string" },
      { indexed: true, internalType: "address", name: "bidder", type: "address" },
    ],
    name: "BidPlaced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "string", name: "auctionId", type: "string" },
      { indexed: true, internalType: "address", name: "bidder", type: "address" },
    ],
    name: "BidUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "string", name: "auctionId", type: "string" },
      { indexed: false, internalType: "uint256", name: "bidderCount", type: "uint256" },
    ],
    name: "BidRevealPrepared",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "string", name: "auctionId", type: "string" },
      { indexed: false, internalType: "address", name: "winner", type: "address" },
      { indexed: false, internalType: "uint256", name: "winningBid", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "bidderCount", type: "uint256" },
    ],
    name: "BidsRevealed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "string", name: "auctionId", type: "string" },
      { indexed: true, internalType: "address", name: "bidder", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "BondClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "string", name: "auctionId", type: "string" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "SellerWithdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "string", name: "auctionId", type: "string" },
      { indexed: true, internalType: "address", name: "winner", type: "address" },
      { indexed: false, internalType: "uint256", name: "amountPaid", type: "uint256" },
    ],
    name: "WinnerSettled",
    type: "event",
  },
  {
    inputs: [],
    name: "MAX_DURATION",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MIN_DURATION",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "auctionId", type: "string" }],
    name: "cancelAuction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "auctionId", type: "string" }],
    name: "claimBond",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "auctionId", type: "string" },
      { internalType: "string", name: "metadataURI", type: "string" },
      { internalType: "uint256", name: "minBid", type: "uint256" },
      { internalType: "uint256", name: "buyNowPrice", type: "uint256" },
      { internalType: "uint256", name: "duration", type: "uint256" },
      { internalType: "uint256", name: "bidBond", type: "uint256" },
    ],
    name: "createAuction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "auctionId", type: "string" }],
    name: "enablePublicBidReveal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllAuctionIds",
    outputs: [{ internalType: "string[]", name: "", type: "string[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "auctionId", type: "string" }],
    name: "getAuction",
    outputs: [
      { internalType: "bool", name: "exists", type: "bool" },
      { internalType: "address", name: "seller", type: "address" },
      { internalType: "string", name: "metadataURI", type: "string" },
      { internalType: "uint256", name: "minBid", type: "uint256" },
      { internalType: "uint256", name: "buyNowPrice", type: "uint256" },
      { internalType: "uint256", name: "bidBond", type: "uint256" },
      { internalType: "uint256", name: "startTime", type: "uint256" },
      { internalType: "uint256", name: "endTime", type: "uint256" },
      { internalType: "bool", name: "cancelled", type: "bool" },
      { internalType: "bool", name: "settled", type: "bool" },
      { internalType: "address", name: "winner", type: "address" },
      { internalType: "uint256", name: "winningBid", type: "uint256" },
      { internalType: "uint256", name: "amountPaid", type: "uint256" },
      { internalType: "uint256", name: "bidderCount", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAuctionCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "auctionId", type: "string" }],
    name: "getBidHandles",
    outputs: [{ internalType: "bytes32[]", name: "", type: "bytes32[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "auctionId", type: "string" },
      { internalType: "address", name: "bidder", type: "address" },
    ],
    name: "getBidSummary",
    outputs: [
      { internalType: "bool", name: "exists", type: "bool" },
      { internalType: "bool", name: "revealed", type: "bool" },
      { internalType: "uint64", name: "revealedAmount", type: "uint64" },
      { internalType: "uint256", name: "bondPaid", type: "uint256" },
      { internalType: "bool", name: "bondClaimed", type: "bool" },
      { internalType: "bool", name: "isWinner", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "auctionId", type: "string" }],
    name: "getBidders",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "auctionId", type: "string" },
      { internalType: "bytes32", name: "encryptedBid", type: "bytes32" },
      { internalType: "bytes", name: "proof", type: "bytes" },
    ],
    name: "placeEncryptedBid",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "auctionId", type: "string" }],
    name: "sellerWithdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "auctionId", type: "string" },
      { internalType: "bytes", name: "cleartexts", type: "bytes" },
      { internalType: "bytes", name: "decryptionProof", type: "bytes" },
    ],
    name: "submitAuctionReveal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "auctionId", type: "string" }],
    name: "settleWinningBid",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "auctionId", type: "string" },
      { internalType: "bytes32", name: "newEncryptedBid", type: "bytes32" },
      { internalType: "bytes", name: "proof", type: "bytes" },
    ],
    name: "updateEncryptedBid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
